server:
  port: ${APP_PORT}

spring:
  profiles:
    active:
      - ${APP_ENVIRONMENT}
  jackson:
    default-property-inclusion: non_null

infrastructure:
  aws-region: ${APP_AWS_REGION}
  book-data-table:
    name: ${APP_AWS_DYNAMODB_BOOK_DATA_TABLE_NAME}
  customer-data-table:
    name: ${APP_AWS_DYNAMODB_CUSTOMER_DATA_TABLE_NAME}
  book-images-bucket:
    url: ${APP_AWS_S3_BOOK_IMAGES_BUCKET_URL}
    name: ${APP_AWS_S3_BOOK_IMAGES_BUCKET_NAME}
  elasticache-cluster:
    url: ${APP_AWS_ELASTICACHE_CLUSTER_URL}
    port: ${APP_AWS_ELASTICACHE_CLUSTER_PORT}
    time-to-live: ${APP_AWS_ELASTICACHE_CLUSTER_TTL} # in seconds
  book-notifications-topic:
    arn: ${APP_AWS_SNS_NOTIFICATIONS_TOPIC_ARN}

book-api:
  validation:
    min-published-year: 1800
  message-templates:
    book-added: A new book is available! It is %s, written by %s.
    book-removed: A book is no longer available! It was %s, written by %s.

logging:
  level:
    com.epam.cloudx.aws: ${LOG_LEVEL:INFO}
  file:
    path: .

