server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null

infrastructure:
  aws-region: eu-central-1
  # endpoints of the localstack services
  s3-localstack-endpoint: http://localhost:4566
  dynamodb-localstack-endpoint: http://localhost:4566
  sns-localstack-endpoint: http://localhost:4566
  book-data-table:
    name: CloudxBookData
  customer-data-table:
    name: CloudxCustomerData
  book-images-bucket:
    url: http://localhost:4566/s3/cloudx-book-cover-images
    name: cloudx-book-cover-images
  elasticache-cluster:
    url: localhost
    port: 11211
    time-to-live: 60 # in seconds
  book-notifications-topic:
    arn: arn:aws:sns:eu-central-1:000000000000:cloudx-book-notifications

book-api:
  validation:
    min-published-year: 1800
  message-templates:
    book-added: A new book is available! It is %s, written by %s.
    book-removed: A book is no longer available! It was %s, written by %s.

logging:
  level:
    com.gaspar.cloudx.aws: DEBUG
  file:
    path: .