spring:
  profiles:
    active:
      - ${ENVIRONMENT}
  jackson:
    default-property-inclusion: non_null

infrastructure:
  aws-region: ${AWS_REGION}
  book-data-table:
    name: ${AWS_DYNAMODB_BOOK_DATA_TABLE_NAME}

  book-images-bucket:
    name: ${AWS_S3_BOOK_IMAGES_BUCKET_NAME}

book-api:
  validation:
    min-published-year: 1800
