server:
  port: 8080

spring:
  profiles:
    active:
      - dev
  jackson:
    default-property-inclusion: non_null


infrastructure:
  aws-region: eu-central-1
  # endpoints of the localstack services
  s3-localstack-endpoint: http://localhost:4566
  dynamodb-localstack-endpoint: http://localhost:4566
  book-data-table:
    name: EpamCloudxBookData
  book-images-bucket:
    url: http://localhost:4566/s3/epam-cloudx-book-cover-images
    name: epam-cloudx-book-cover-images

book-api:
  validation:
    min-published-year: 1800

logging:
  level:
    com.epam.cloudx.aws: DEBUG